In [162]:
import pandas as pd

In [163]:
df = pd.read_csv('index.csv', names=['ID','index'])
df.drop(0, inplace=True)
df.reset_index(inplace=True)
df.drop('level_0', axis=1, inplace=True)

In [164]:
df.loc[:,'index'] = df.loc[:,'index'].map(lambda x: (5-len(x))*'0' + x)

In [165]:
four_digits = ['0127d0',
     '012e2f',
     '066aaa',
     '07d00c',
     '081204',
     '095078',
     '0968cc',
     '0da303',
     '0d1801',
     '0e6201',
     '0ec255',
     '0f1f4d',
     '10efaf',
     '10f28d',
     '116c83',
     '186e7f',
     '180718',
     '19d49d',
     '1a17b2',
     '1a7097',
     '1b79dc',
     '1be84b',
     '20fe64',
     '2290b4',
     '2669b5',
     '269953',
     '292c58',
     '29f796',
     '2bbad8',
     '2c3aa4',
     '2ce0ef',
     '31603a',
     '3196e8',
     '3723f6',
     '37a08e',
     '3b0812',
     '3c95cc',
     '3e3a50',
     '430e1c',     
     '432351',
     '45eaf0',
     '4642e0',
     '47832b',
     '48349f',     
     '48bea7',
     '4b8f33',
     '4c27a0',
     '534968',
     '536b85',     
     '57c155',
     '5a5105',
     '601a9f',
     '628be4',
     '6750e5',     
     '6fb2f1',
     '71311a',
     '76de68',
     '77b250',
     '77d9a4',     
     '7859fe',
     '79ecf1',
     '7c76e1',
     '806f01',
     '835cf1',
     '86dffb',
     '8ba70b',
     '8db156',
     '8f3de1',
     '8f52ae',
     '90a6f3',
     '92c418',
     '93c5fd',
     '952423',
     '974838',
     '9831a0',
     '9895ad',
     '9a9e70',
     '9b8b61',
     '9b960d',
     '9bd67d',
     '9e4ed4',
     'a0d62a',
     'a12817',
     'a15a18',
     'a34a65',
     'a472ae',
     'a4c005',
     'a96421',
     'aaa324',
     'ab9e6f',
     'ae3244',
     'b0cda7',
     'b0d371',
     'b24c39',
     'b506c2',
     'b562d5',
     'b6bc93',
     'b74fb9',
     'b83f1f',
     'b8700e',
     'b92c50',
     'b99b9c',
     'ba405e',
     'baeb02',
     'bb28ac',
     'bcb2d8',
     'be0f44',
     'bee7ca',
     'bf6aaf',
     'c7e272',
     'c9802d',
     'c9c6c8',
     'cc57e7',
     'ce0566',
     'ce90aa',
     'd144ce',
     'd1ce0f',
     'd2c139',
     'd46813',
     'd4f5ae',
     'd72a5f',
     'd8912a',
     'da383d',
     'dbd857',
     'dc0a2e',
     'e1f2b5',
     'e6ebae',
     'e77c2d',
     'ec07f5',
     'ed10d5',
     'efbec8',
     'f01920',
     'f074ce',
     'f1dcf2',
     'f54ac4',
     'f7578f',
     'f8c691']

In [166]:
for d in four_digits:
    df.loc[df.ID == d, 'index'] = df.loc[df.ID == d, 'index'].values[0][1:]

In [167]:
df

         ID  index
0    0127d0   1416
1    012e2f   2556
2    01a650  00250
3    0249c2  00129
4    027912  01025
..      ...    ...
789  fe5bf4  00289
790  ff7912  00624
791  ff9175  00472
792  ffbff4  01169
793      ID  index

[794 rows x 2 columns]

In [123]:
df.iloc[df[df.ID == '0127d0'].index]

       ID index
0  0127d0  1416

In [63]:
df[df.ID == '0127d0']['index'].values[0][1:]

'1416'

In [91]:
df.set_index('ID').loc[four_digits, 'index'].map(lambda x: x[1:])

ID
0127d0    1416
012e2f    2556
066aaa    0879
07d00c    3806
081204    0550
          ...
f074ce    0701
f1dcf2    0701
f54ac4    1762
f7578f    2250
f8c691    3478
Name: index, Length: 137, dtype: object

In [94]:
for d in four_digits:
    df.loc[df[df].index-,'index']  df[df.ID == d]['index'].values[0][1:]

1416
2556
0879
3806
0550
0969
0113
0679
0758
1237
3351
1731
0770
3103
1561
3100
2520
0889
0878
1818
0828
1111
3247
1416
5344
2182
3784
0961
1380
1635
1527
2386
3069
4497
0758
5376
1610
2081
0563
3819
0841
2366
3490
2940
0561
0326
0490
6603
2845
0657
0454
1037
1762
1979
1488
0771
0768
2269
0323
2908
0716
0754
0203
1216
0696
0408
1085
0841
1117
1437
1616
1139
1232
2039
1269
2426
1652
6603
2036
1216
4092
1506
3923
3185
0001
1521
0874
2611
3662
1188
4278
0955
0722
4116
1290
5183
1040
1299
0627
0240
1365
0336
0975
2520
5045
1370
2304
0770
0496
0304
1416
3958
2234
3318
1632
0295
1859
0952
1642
0575
0300
1186
4211
1044
1080
2930
0838
3998
1843
4884
1631
1472
0701
0701
1762
2250
3478

In [60]:
four_digits = ['0127d0',
     '012e2f',
     '066aaa',
     '07d00c',
     '081204',
     '095078',
     '0968cc',
     '0da303',
     '0d1801',
     '0e6201',
     '0ec255',
     '0f1f4d',
     '10efaf',
     '10f28d',
     '116c83',
     '186e7f',
     '180718',
     '19d49d',
     '1a17b2',
     '1a7097',
     '1b79dc',
     '1be84b',
     '20fe64',
     '2290b4',
     '2669b5',
     '269953',
     '292c58',
     '29f796',
     '2bbad8',
     '2c3aa4',
     '2ce0ef',
     '31603a',
     '3196e8',
     '3723f6',
     '37a08e',
     '3b0812',
     '3c95cc',
     '3e3a50',
     '430e1c',     
     '432351',
     '45eaf0',
     '4642e0',
     '47832b',
     '48349f',     
     '48bea7',
     '4b8f33',
     '4c27a0',
     '534968',
     '536b85',     
     '57c155',
     '5a5105',
     '601a9f',
     '628be4',
     '6750e5',     
     '6fb2f1',
     '71311a',
     '76de68',
     '77b250',
     '77d9a4',     
     '7859fe',
     '79ecf1',
     '7c76e1',
     '806f01',
     '835cf1',
     '86dffb',
     '8ba70b',
     '8db156',
     '8f3de1',
     '8f52ae',
     '90a6f3',
     '92c418',
     '93c5fd',
     '952423',
     '974838',
     '9831a0',
     '9895ad',
     '9a9e70',
     '9b8b61',
     '9b960d',
     '9bd67d',
     '9e4ed4',
     'a0d62a',
     'a12817',
     'a15a18',
     'a34a65',
     'a472ae',
     'a4c005',
     'a96421',
     'aaa324',
     'ab9e6f',
     'ae3244',
     'b0cda7',
     'b0d371',
     'b24c39',
     'b506c2',
     'b562d5',
     'b6bc93',
     'b74fb9',
     'b83f1f',
     'b8700e',
     'b92c50',
     'b99b9c',
     'ba405e',
     'baeb02',
     'bb28ac',
     'bcb2d8',
     'be0f44',
     'bee7ca',
     'bf6aaf',
     'c7e272',
     'c9802d',
     'c9c6c8',
     'cc57e7',
     'ce0566',
     'ce90aa',
     'd144ce',
     'd1ce0f',
     'd2c139',
     'd46813',
     'd4f5ae',
     'd72a5f',
     'd8912a',
     'da383d',
     'dbd857',
     'dc0a2e',
     'e1f2b5',
     'e6ebae',
     'e77c2d',
     'ec07f5',
     'ed10d5',
     'efbec8',
     'f01920',
     'f074ce',
     'f1dcf2',
     'f54ac4',
     'f7578f',
     'f8c691']